# Generated by Django 6.0.1 on 2026-01-21 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="detections/%Y/%m/%d/")),
                ("detections", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_events",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Event",
                "verbose_name_plural": "Detection Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
