# Generated by Django 6.0.1 on 2026-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionevent",
            name="person_id",
            field=models.CharField(blank=True, default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="detectionevent",
            name="person_name",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
    ]
