"""
LLM 智能报告生成器
基于当日违规数据生成 Markdown 格式的安全报告（接入 OpenAI/DeepSeek API）
"""
import json
import requests
from collections import Counter

from django.conf import settings
from django.utils import timezone

# 使用 DetectionEvent（ppe 应用中的检测事件模型）
from ppe.models import DetectionEvent


def _normalize_violation_label(raw: str) -> str:
    """将 raw 违规类型转为可读标签，如 no_helmet -> No Helmet"""
    if not raw:
        return "Unknown"
    s = str(raw).strip().lower().replace("_", " ").replace("-", " ")
    return s.title() if s else "Unknown"


def _extract_violations_from_detections(detections) -> list[str]:
    """
    从 detections JSON 中提取违规类型列表。
    支持格式: {'items': [{'class': '...'}, ...]} 或 {'violation': '...'} 或单条 {'class': '...'}
    """
    out = []
    if not isinstance(detections, dict):
        return out
    items = detections.get("items")
    if items and isinstance(items, list):
        for it in items:
            if isinstance(it, dict):
                label = it.get("class") or it.get("violation")
                if label:
                    out.append(str(label).strip())
    else:
        label = detections.get("class") or detections.get("violation")
        if label:
            out.append(str(label).strip())
    return out


def generate_daily_report(customer):
    """
    生成指定客户当日的安全报告（Markdown 文本）。
    数据来源: DetectionEvent（当日、该客户）。
    """
    today = timezone.now().date()
    events = DetectionEvent.objects.filter(
        customer=customer,
        timestamp__date=today,
    ).order_by("-timestamp")

    total_violations = 0
    type_counts: Counter = Counter()
    camera_counts: Counter = Counter()

    for ev in events:
        camera_counts[ev.camera_id] += 1
        violations = _extract_violations_from_detections(ev.detections)
        if violations:
            for v in violations:
                type_counts[_normalize_violation_label(v)] += 1
                total_violations += 1
        else:
            # 无具体类型时，按事件计为 1 次违规
            type_counts["General"] += 1
            total_violations += 1

    # 违规最多的摄像头
    hotspot_camera = ""
    if camera_counts:
        hotspot_camera = camera_counts.most_common(1)[0][0]

    # 合规程度描述（基于当日违规数简单分级）
    if total_violations == 0:
        compliance_desc = "Excellent"
    elif total_violations <= 3:
        compliance_desc = "Good"
    elif total_violations <= 10:
        compliance_desc = "Moderate"
    else:
        compliance_desc = "Low"

    # 按数量排序的违规类型
    sorted_types = type_counts.most_common()
    key_violations_lines = []
    for label, cnt in sorted_types:
        emphasis = " (Critical!)" if cnt >= 3 else ""
        key_violations_lines.append(f"- **{label}**: {cnt} incident(s){emphasis}")

    key_violations_md = "\n".join(key_violations_lines) if key_violations_lines else "- No specific violation types recorded."

    hotspot_md = (
        f"Most violations occurred at **{hotspot_camera}**. Please inspect this area."
        if hotspot_camera
        else "No camera hotspot data available for today."
    )

    if total_violations == 0:
        summary = "Today, we detected **no violations**. The safety compliance level is **Excellent**."
    else:
        summary = f"Today, we detected a total of **{total_violations}** violation(s). The safety compliance level is **{compliance_desc}**."

    # 构建数据摘要（用于 LLM Prompt）
    violations_detail = ", ".join([f"{label}: {cnt}" for label, cnt in sorted_types]) if sorted_types else "None"
    
    # 尝试调用 LLM API 生成报告
    llm_report = _generate_report_with_llm(
        customer_name=customer.name,
        date=today.strftime('%Y-%m-%d'),
        total_violations=total_violations,
        compliance_desc=compliance_desc,
        violations_detail=violations_detail,
        hotspot_camera=hotspot_camera,
        key_violations_md=key_violations_md,
        hotspot_md=hotspot_md,
    )
    
    # 如果 LLM 调用成功，返回 AI 生成的报告；否则使用模板报告
    if llm_report:
        return llm_report
    
    # Fallback: 使用硬编码模板
    report = f"""## 🛡️ Daily Safety Report - {customer.name}
**Date**: {today.strftime('%Y-%m-%d')}

### 📊 Summary
{summary}

### 🚫 Key Violations
{key_violations_md}

### 📍 Hotspots
{hotspot_md}

---
*Generated by AI Enterprise OS*
"""
    return report.strip()


def _generate_report_with_llm(customer_name, date, total_violations, compliance_desc, 
                                violations_detail, hotspot_camera, key_violations_md, hotspot_md):
    """
    调用 LLM API 生成报告
    
    Returns:
        str: AI 生成的报告文本，如果失败则返回 None
    """
    # 检查是否有 API Key
    api_key = getattr(settings, 'LLM_API_KEY', None)
    if not api_key or api_key == '':
        print("[Report Generator] No LLM API key configured, using template fallback")
        return None
    
    api_base = getattr(settings, 'LLM_API_BASE', 'https://api.openai.com/v1')
    model = getattr(settings, 'LLM_MODEL', 'gpt-4o-mini')
    
    # 构建 Prompt (English)
    prompt = f"""You are a professional Safety Officer at a factory. Analyze the following violation data and generate a concise Daily Safety Report in Markdown format.

**Data Summary:**
- Customer Name: {customer_name}
- Date: {date}
- Total Violations: {total_violations}
- Compliance Level: {compliance_desc}
- Violation Details: {violations_detail}
- Hotspot Camera: {hotspot_camera if hotspot_camera else "None"}

**Requirements:**
1. Use Markdown format
2. Include sections: Title, Summary, Key Violations, Hotspots
3. Professional but clear language
4. If violations = 0, emphasize excellent safety performance
5. If violations exist, provide constructive recommendations
6. Use appropriate emojis for readability
7. **IMPORTANT: Generate the entire report in English only**

Please generate the report:"""
    
    # 准备请求
    # DeepSeek API 端点: https://api.deepseek.com/chat/completions
    # 确保 URL 拼接正确（移除末尾斜杠，然后添加 /chat/completions）
    url = f"{api_base.rstrip('/')}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": model,  # 使用 settings.LLM_MODEL（deepseek-chat）
        "messages": [
            {
                "role": "system",
                "content": "You are a professional Safety Officer at a factory. Analyze violation data and generate concise Daily Safety Reports in Markdown format. Use professional tone. English only."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "temperature": 0.7,
        "max_tokens": 1000,
        "stream": False  # DeepSeek 支持流式，这里设为 False 获取完整响应
    }
    
    try:
        print(f"[Report Generator] Calling LLM API: {url} (model: {model})")
        # 120 秒超时：本地 Ollama 可能需要更长时间，给予 2 分钟等待时间
        response = requests.post(url, headers=headers, json=payload, timeout=120)
        response.raise_for_status()
        
        result = response.json()
        
        # 提取生成的报告内容
        if 'choices' in result and len(result['choices']) > 0:
            report_content = result['choices'][0]['message']['content']
            print("[Report Generator] LLM report generated successfully")
            return report_content.strip()
        else:
            print("[Report Generator] Invalid response format from LLM API")
            return None
            
    except requests.exceptions.Timeout:
        print(f"[Report Generator] LLM API request timeout (120s exceeded)")
        return None
    except requests.exceptions.RequestException as e:
        print(f"[Report Generator] LLM API request failed: {e}")
        return None
    except (KeyError, IndexError, json.JSONDecodeError) as e:
        print(f"[Report Generator] Failed to parse LLM response: {e}")
        return None
    except Exception as e:
        print(f"[Report Generator] Unexpected error: {e}")
        return None
