"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9%^*ep!_#*)r0^@k-5ek%5eo7t@bwz%#3=#l^8zmb+ee&zy&x$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework',  
    'core',            # <--- 必须要有这一行！
    'ppe',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise 静态文件服务（必须在 SecurityMiddleware 之后）
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.SubscriptionCheckMiddleware",  # 订阅过期检查中间件（放在 AuthenticationMiddleware 之后）
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.subscribed_modules",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 告诉 Django 用 MySQL
        'NAME': 'ai_platform_db',              # 刚才在 Workbench 建的库名
        'USER': 'root',                        # 用户名
        'PASSWORD': 'root',                 # ★★★ 这里一定要填你进 Workbench 输的那个密码！
        'HOST': '127.0.0.1',
        'PORT': '3308',                        # ★★★ 你的端口是 3308
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise 配置 - 生产环境静态文件服务
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 收集静态文件的目标目录
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # 压缩和缓存静态文件


# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'  # 登录成功后跳到首页
LOGOUT_REDIRECT_URL = 'login'  # 登出后跳回登录页


# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# LLM API Configuration
# 支持从环境变量读取，如果没有则使用默认值
# 当前配置为本地 Ollama（测试用）
# 安全提示：生产环境请使用环境变量或 .env 文件，不要硬编码 API Key
import os

# LLM Configuration (Ollama Local)
# 默认使用本地 Ollama，可通过环境变量覆盖
LLM_API_KEY = os.environ.get('LLM_API_KEY', 'ollama')  # Ollama 不需要真实 Key，填字符串即可
LLM_API_BASE = os.environ.get('LLM_API_BASE', 'http://127.0.0.1:11434/v1')  # Ollama 本地地址
LLM_MODEL = os.environ.get('LLM_MODEL', 'llama3.2')  # 本地模型名称（如 llama3.2, mistral, qwen2.5）

# 如果需要切换回 DeepSeek/OpenAI，取消下面的注释并注释掉上面的配置
# LLM_API_KEY = os.environ.get('LLM_API_KEY', 'sk-7e9fe2396f184bf8959c1e6ba3597bb3')
# LLM_API_BASE = os.environ.get('LLM_API_BASE', 'https://api.deepseek.com')
# LLM_MODEL = os.environ.get('LLM_MODEL', 'deepseek-chat')

# settings.py

# 先填你的手机号
WHATSAPP_PHONE = "60172402829" 

# 暂时填个假的，等机器人醒了再换
WHATSAPP_API_KEY = "WAITING_FOR_KEY" 

WHATSAPP_ENABLED = True